sudo: required

services:
  - docker

language: node_js
node_js:
  - 8

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # install aws
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set default.region eu-central-1

  # get credentials
  - wget --no-cache https://s3.eu-central-1.amazonaws.com/tsmean-credentials/production."$PROD_CREDENTIALS".properties.json -O backend/properties/production.properties.json


  # BACKEND
  ## build
  - docker build -t tsmean/server:"$TRAVIS_BUILD_NUMBER" -f docker/server.dockerfile .
  - docker push tsmean/server:"$TRAVIS_BUILD_NUMBER"
  ## test
  # - docker run tsmean/server npm test
  ## deploy
  -
  - aws ssm send-command --instance-ids "i-0ed7d2d2191c0c2d5" --document-name "AWS-RunShellScript" --parameters commands=["echo hello"]
  - aws ssm send-command --instance-ids "i-0ed7d2d2191c0c2d5" --document-name "AWS-RunShellScript" --parameters commands=["rm docker-compose.yml"]
  - aws ssm send-command --instance-ids "i-0ed7d2d2191c0c2d5" --document-name "AWS-RunShellScript" --parameters commands=["wget --no-cache https://raw.githubusercontent.com/tsmean/tsmean/deploy/docker/docker-compose.yml"]
  - aws ssm send-command --instance-ids "i-0ed7d2d2191c0c2d5" --document-name "AWS-RunShellScript" --parameters commands=["docker stack deploy -c docker-compose.yml tsmean"]


  # FRONTEND
  ## build
  - cd shared
  - npm install
  - cd ../frontend
  - npm install
  - npm run build:prod
  - cd ..

  ## deploy
  - aws configure set preview.cloudfront true
  - aws s3 cp frontend/dist s3://demo.tsmean.com/ --recursive
  - aws cloudfront create-invalidation --distribution-id E194UGLQ78RUJV --paths "/*"

script:
  - echo "everything a ok"
  - echo "wget --no-cache https://raw.githubusercontent.com/tsmean/tsmean/deploy/docker/docker-compose.yml && docker stack deploy -c docker-compose.yml tsmean"
  - echo "rm docker-compose.yml"


# Former frontend build
#  - docker build -t tsmean/client:"$TRAVIS_BUILD_NUMBER" -f docker/client.dockerfile .
#  - docker push tsmean/client:"$TRAVIS_BUILD_NUMBER"
#  - id=$(docker create tsmean/client:"$TRAVIS_BUILD_NUMBER")
#  - docker cp $id:/code/frontend/dist frontend/dist
#  - docker rm -v $id
