sudo: required

services:
  - docker

install:
  - docker build -t tsmean/server -f docker/server.dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tsmean/server

script:
  - echo "everything a ok"
  - docker swarm join --token "$SWARM_TOKEN" 172.31.31.235:2377
  - docker stack deploy -c docker/docker-compose.yml tsmean
  - docker swarm leave

