sudo: required

services:
  - docker

install:
  - docker build -t tsmean/server:"$TRAVIS_BUILD_NUMBER" -f docker/server.dockerfile .
  # - docker run tsmean/server npm test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tsmean/server:"$TRAVIS_BUILD_NUMBER"

script:
  - echo "to deploy, login to your swarm and run:"
  - echo "wget --no-cache https://raw.githubusercontent.com/tsmean/tsmean/deploy/docker/docker-compose.yml && docker stack deploy -c docker-compose.yml tsmean"
  - echo "rm docker-compose.yml"
