sudo: required

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # get credentials
  - wget --no-cache https://s3.eu-central-1.amazonaws.com/tsmean-credentials/production."$PROD_CREDENTIALS".properties.json -O backend/properties

  - docker build -t tsmean/server:"$TRAVIS_BUILD_NUMBER" -f docker/server.dockerfile .
  # - docker run tsmean/server npm test
  - docker push tsmean/server:"$TRAVIS_BUILD_NUMBER"
  - docker build -t tsmean/client:"$TRAVIS_BUILD_NUMBER" -f docker/client.dockerfile .
  - docker push tsmean/client:"$TRAVIS_BUILD_NUMBER"


script:
  - echo "to deploy, login to your swarm and run:"
  - echo "wget --no-cache https://raw.githubusercontent.com/tsmean/tsmean/deploy/docker/docker-compose.yml && docker stack deploy -c docker-compose.yml tsmean"
  - echo "rm docker-compose.yml"
